# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dpalacio <dpalacio@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/07 11:54:37 by dpalacio          #+#    #+#              #
#    Updated: 2021/06/07 11:57:17 by dpalacio         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

TEXT = "42 is for the braves"
TEXT2 = "and for the crazy"

say_the_thing:
	echo $(TEXT)

say_the_truth: say_the_thing
	echo $(TEXT2)
